CREATE TABLE `member` (
                          `id`	INT	NOT NULL,
                          `password`	VARCHAR(255)	NOT NULL,
                          `employee_number`	INT	NOT NULL,
                          `name`	VARCHAR(255)	NOT NULL,
                          `birth`	VARCHAR(255)	NULL,
                          `phone`	VARCHAR(255)	NOT NULL,
                          `picture_url`	VARCHAR(255)	NOT NULL,
                          `email`	VARCHAR(255)	NOT NULL,
                          `address`	VARCHAR(255)	NOT NULL,
                          `vacation_count`	INT	NOT NULL	DEFAULT 0,
                          `hire_at`	DATETIME	NOT NULL,
                          `resign_at`	DATETIME	NULL,
                          `created_at`	DATETIME	NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          `created_member_id`	INT	NULL,
                          `deleted_member_id`	INT	NULL,
                          `updated_at`	DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                          `updated_member_id`	INT	NOT NULL,
                          `last_login_at`	DATETIME	NULL,
                          `status`	TINYINT NOT NULL CHECK (status IN (0, 1)),
--                           `department_id`	INT	NULL,
--                           `position_id`	INT	NULL,
--                           `job_id`	INT	NULL,
--                           `rank_id`	INT	NULL
                          PRIMARY KEY (`id`)
);