export const RoleCode = {
    USER: 'ROLE_USER',
    HR_ACCESS: 'ROLE_HR_ACCESS',
    RECRUITMENT_PLAN_EDITOR: 'ROLE_RECRUITMENT_PLAN_EDITOR',
    APPROVAL_PROCESSOR: 'ROLE_APPROVAL_PROCESSOR',
    RECRUITMENT_OPERATOR: 'ROLE_RECRUITMENT_OPERATOR',
};